project1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("new", views.new, name="new"),
    path("random", views.random, name="random"),
    path("<str:title>", views.entry, name="entry"),
    path("<str:title>/edit", views.edit, name="edit")
]

project1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

project1/wiki/encyclopedia/views.py
from random import randrange

from django import forms
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from markdown2 import markdown

from . import util


class NewEntryForm(forms.Form):
    title = forms.CharField(label="Entry Title")
    content = forms.CharField(
            label="Markdown Content",
            widget=forms.Textarea(attrs={
                "class": "responsive-text-area"
            })
    )


def index(request):
    return render(request, "encyclopedia/index.html", {
        "titles": util.list_entries()
    })


# return a wiki entry
def entry(request, title):
    if util.get_entry(title):
        return renderEntry(request, title)
    else:
        return entryNotFound(request, title)


# search for an entry
def search(request):

    # implemented without Django Forms as an exercise
    title = request.POST.get("q")
    if util.get_entry(title):
        return renderEntry(request, title)
    else:

        # return entries with titles containing the search string
        results = [entry for entry in util.list_entries()
                   if title.lower() in entry.lower()]
        if len(results) > 0:
            return render(request, "encyclopedia/results.html", {
                "titles": results
            })
        else:
            return entryNotFound(request, title)


# create a new entry
def new(request):

    # retrieve, validate and save form input
    if request.method == "POST":
        form = NewEntryForm(request.POST, False)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]

            # if a entry with already exists
            if title in util.list_entries():
                return render(request, "encyclopedia/entry_exists.html", {
                    "title": title
                })
            else:
                util.save_entry(title, content)
                return HttpResponseRedirect(
                        reverse("wiki:entry", args=(title,))
                )

        # invalid form input
        else:
            return render(request, "encyclopedia/new.html", {
                "form": form
            })

    # new form
    else:
        return render(request, "encyclopedia/new.html", {
            "form": NewEntryForm(),
            "title": "New Entry"
        })


# edit an existing entry
def edit(request, title):

    # retrieve, validate and save form input
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("wiki:entry", args=(title,)))

        # invalid form input
        else:
            return render(request, "encyclopedia/new.html", {
                "form": form
            })

    # editing form
    else:
        content = markdown(util.get_entry(title))
        return render(request, "encyclopedia/new.html", {
            "form": NewEntryForm(initial={
                "content": content,
                "title": "Title cannot be changed"
            }),
            "title": title
        })


# redirect to a random entry
def random(request):
    entries = util.list_entries()
    random_entry = randrange(len(entries))
    return HttpResponseRedirect(
            reverse("wiki:entry", args=(entries[random_entry],))
    )


# helper function to display an entry
def renderEntry(request, title):
    content = markdown(util.get_entry(title))
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "content": content
    })


# helper function to display entry not found page
def entryNotFound(request, title):
    return render(request, "encyclopedia/entry404.html", {
            "title": title
        })

project1/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

    {{ content | safe }}

    <a href="{% url 'wiki:edit' title %}">Edit this page</a>
{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/entry404.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Entry Not Found
{% endblock %}

{% block body %}
    <h1>Entry Not Found</h1>
    <br>
    <p>No result for an entry named {{ title }}. <a href="{% url 'wiki:new' %}">Create it?</a></p>

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/entry_exists.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Entry Exists
{% endblock %}

{% block body %}
    <h1>Entry Exists</h1>
    <br>
    <p>
        A page for <a href="{% url 'wiki:entry' title %}">{{ title }}</a> already exists.
    </p>
{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for title in titles %}
            <li>
                <a href="{% url 'wiki:entry' title %}">{{ title }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="post">
                    {% csrf_token %}

                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project1/wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>
    {% if title == "New Entry" %}
        <form action="{% url 'wiki:new' %}" method="post">
    {% else %}
        <form action="{% url 'wiki:edit' title %}" method="post">
    {% endif %}
            {% csrf_token %}
            {% for field in form %}
                {{ field.errors }}
                {{ field.label_tag }} 
                <br>
                {{ field }}
                <br>
            {% endfor %}
            <br>    
            <input type="submit">
        </form>
{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for title in titles %}
            <li>
                <a href="{% url 'wiki:entry' title  %}">{{ title }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}